apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "spring-cloud-config-server.fullname" . }}
  labels:
{{ include "spring-cloud-config-server.labels" . | indent 4 }}
data:
  gitUsername: {{ .Values.secrets.gitUsername }}
  gitPassword: {{ .Values.secrets.gitPassword }}
